    spring:
      datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://fordevel:5432/
        username: ForestDev
        password: ForestDev1
      jpa:
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            show_sql: true
            temp:
              use_jdbc_metadata_defaults: false
